-- ============================================================
-- Word Guess Who: Seed Data
-- System (bundled) game configurations — instructor_id is NULL
-- Source of truth: configs/*.json
-- ============================================================

INSERT INTO game_configs (id, name, instructor_id, config_json, is_public) VALUES

('default', 'Kindergarten Dolch Sight Words', NULL, '{
  "id": "default",
  "name": "Kindergarten Dolch Sight Words",
  "description": "The classic Dolch sight word list for kindergarten, featuring 24 high-frequency words that young readers should recognize instantly.",
  "wordBank": [
    {"word": "the", "category": "primer"},
    {"word": "to", "category": "primer"},
    {"word": "and", "category": "primer"},
    {"word": "a", "category": "primer"},
    {"word": "I", "category": "primer"},
    {"word": "you", "category": "primer"},
    {"word": "it", "category": "primer"},
    {"word": "in", "category": "primer"},
    {"word": "said", "category": "primer"},
    {"word": "for", "category": "primer"},
    {"word": "up", "category": "primer"},
    {"word": "look", "category": "primer"},
    {"word": "is", "category": "pre-primer"},
    {"word": "go", "category": "pre-primer"},
    {"word": "we", "category": "pre-primer"},
    {"word": "little", "category": "pre-primer"},
    {"word": "down", "category": "pre-primer"},
    {"word": "can", "category": "pre-primer"},
    {"word": "see", "category": "pre-primer"},
    {"word": "not", "category": "pre-primer"},
    {"word": "one", "category": "pre-primer"},
    {"word": "my", "category": "pre-primer"},
    {"word": "me", "category": "pre-primer"},
    {"word": "big", "category": "pre-primer"}
  ],
  "suggestedQuestions": [
    {"text": "Does your word have the letter ''e''?", "category": "letters"},
    {"text": "Does your word have the letter ''o''?", "category": "letters"},
    {"text": "Does your word have the letter ''a''?", "category": "letters"},
    {"text": "Does your word have the letter ''i''?", "category": "letters"},
    {"text": "Does your word start with a vowel?", "category": "letters"},
    {"text": "Does your word end with a vowel?", "category": "letters"},
    {"text": "Is your word only one letter?", "category": "length"},
    {"text": "Is your word two letters long?", "category": "length"},
    {"text": "Is your word three letters long?", "category": "length"},
    {"text": "Is your word more than three letters?", "category": "length"},
    {"text": "Does your word have a double letter?", "category": "patterns"},
    {"text": "Does your word start with a tall letter (like ''l'' or ''d'')?", "category": "patterns"},
    {"text": "Does your word have a letter that goes below the line (like ''g'' or ''y'')?", "category": "patterns"},
    {"text": "Does your word rhyme with ''go''?", "category": "sounds"},
    {"text": "Does your word rhyme with ''see''?", "category": "sounds"},
    {"text": "Does your word start with the same sound as ''sun''?", "category": "sounds"},
    {"text": "Is your word something you can do (an action)?", "category": "meaning"},
    {"text": "Is your word a person (like ''I'' or ''you'')?", "category": "meaning"}
  ],
  "settings": {"gridSize": 24, "allowCustomQuestions": true, "turnTimeLimit": 0, "showPhoneticHints": false, "enableSounds": true}
}', TRUE),

('grade-prek', 'Pre-K Sight Words', NULL, '{
  "id": "grade-prek",
  "name": "Pre-K Sight Words",
  "description": "Dolch Pre-Primer sight words for Pre-K learners — the first high-frequency words children encounter.",
  "wordBank": [
    {"word": "a", "category": "pre-primer"},
    {"word": "and", "category": "pre-primer"},
    {"word": "big", "category": "pre-primer"},
    {"word": "blue", "category": "pre-primer"},
    {"word": "can", "category": "pre-primer"},
    {"word": "come", "category": "pre-primer"},
    {"word": "down", "category": "pre-primer"},
    {"word": "find", "category": "pre-primer"},
    {"word": "for", "category": "pre-primer"},
    {"word": "go", "category": "pre-primer"},
    {"word": "help", "category": "pre-primer"},
    {"word": "I", "category": "pre-primer"},
    {"word": "in", "category": "pre-primer"},
    {"word": "is", "category": "pre-primer"},
    {"word": "it", "category": "pre-primer"},
    {"word": "look", "category": "pre-primer"},
    {"word": "me", "category": "pre-primer"},
    {"word": "my", "category": "pre-primer"},
    {"word": "not", "category": "pre-primer"},
    {"word": "one", "category": "pre-primer"},
    {"word": "red", "category": "pre-primer"},
    {"word": "run", "category": "pre-primer"},
    {"word": "see", "category": "pre-primer"},
    {"word": "up", "category": "pre-primer"}
  ],
  "suggestedQuestions": [
    {"text": "Does your word have the letter ''e''?", "category": "letters"},
    {"text": "Does your word have the letter ''o''?", "category": "letters"},
    {"text": "Does your word start with a vowel?", "category": "letters"},
    {"text": "Is your word only one letter?", "category": "length"},
    {"text": "Is your word two letters long?", "category": "length"},
    {"text": "Is your word three letters long?", "category": "length"},
    {"text": "Is your word more than three letters?", "category": "length"},
    {"text": "Does your word start with a tall letter (like ''b'' or ''d'')?", "category": "patterns"},
    {"text": "Does your word have a letter that goes below the line (like ''g'' or ''y'')?", "category": "patterns"},
    {"text": "Does your word rhyme with ''go''?", "category": "sounds"},
    {"text": "Does your word rhyme with ''see''?", "category": "sounds"},
    {"text": "Is your word a color?", "category": "meaning"}
  ],
  "settings": {"gridSize": 24, "allowCustomQuestions": true, "turnTimeLimit": 0, "showPhoneticHints": false, "enableSounds": true}
}', TRUE),

('grade-k', 'Kindergarten Sight Words', NULL, '{
  "id": "grade-k",
  "name": "Kindergarten Sight Words",
  "description": "Dolch Primer sight words for Kindergarten — building on Pre-K with more common words.",
  "wordBank": [
    {"word": "all", "category": "primer"},
    {"word": "am", "category": "primer"},
    {"word": "are", "category": "primer"},
    {"word": "at", "category": "primer"},
    {"word": "ate", "category": "primer"},
    {"word": "be", "category": "primer"},
    {"word": "but", "category": "primer"},
    {"word": "came", "category": "primer"},
    {"word": "did", "category": "primer"},
    {"word": "do", "category": "primer"},
    {"word": "eat", "category": "primer"},
    {"word": "get", "category": "primer"},
    {"word": "good", "category": "primer"},
    {"word": "have", "category": "primer"},
    {"word": "he", "category": "primer"},
    {"word": "into", "category": "primer"},
    {"word": "like", "category": "primer"},
    {"word": "new", "category": "primer"},
    {"word": "no", "category": "primer"},
    {"word": "now", "category": "primer"},
    {"word": "on", "category": "primer"},
    {"word": "our", "category": "primer"},
    {"word": "say", "category": "primer"},
    {"word": "she", "category": "primer"}
  ],
  "suggestedQuestions": [
    {"text": "Does your word have the letter ''e''?", "category": "letters"},
    {"text": "Does your word have the letter ''a''?", "category": "letters"},
    {"text": "Does your word have the letter ''o''?", "category": "letters"},
    {"text": "Does your word start with a vowel?", "category": "letters"},
    {"text": "Does your word end with a vowel?", "category": "letters"},
    {"text": "Is your word two letters long?", "category": "length"},
    {"text": "Is your word three letters long?", "category": "length"},
    {"text": "Is your word more than three letters?", "category": "length"},
    {"text": "Does your word have a double letter?", "category": "patterns"},
    {"text": "Does your word end with the letter ''e''?", "category": "patterns"},
    {"text": "Does your word rhyme with ''go''?", "category": "sounds"},
    {"text": "Is your word something you can do (an action)?", "category": "meaning"},
    {"text": "Is your word a person (like ''he'' or ''she'')?", "category": "meaning"}
  ],
  "settings": {"gridSize": 24, "allowCustomQuestions": true, "turnTimeLimit": 0, "showPhoneticHints": false, "enableSounds": true}
}', TRUE),

('grade-1', '1st Grade Sight Words', NULL, '{
  "id": "grade-1",
  "name": "1st Grade Sight Words",
  "description": "Dolch 1st Grade sight words — words first graders should recognize on sight for fluent reading.",
  "wordBank": [
    {"word": "after", "category": "first"},
    {"word": "again", "category": "first"},
    {"word": "an", "category": "first"},
    {"word": "any", "category": "first"},
    {"word": "ask", "category": "first"},
    {"word": "by", "category": "first"},
    {"word": "could", "category": "first"},
    {"word": "every", "category": "first"},
    {"word": "fly", "category": "first"},
    {"word": "from", "category": "first"},
    {"word": "give", "category": "first"},
    {"word": "going", "category": "first"},
    {"word": "had", "category": "first"},
    {"word": "has", "category": "first"},
    {"word": "her", "category": "first"},
    {"word": "him", "category": "first"},
    {"word": "just", "category": "first"},
    {"word": "know", "category": "first"},
    {"word": "let", "category": "first"},
    {"word": "live", "category": "first"},
    {"word": "old", "category": "first"},
    {"word": "open", "category": "first"},
    {"word": "take", "category": "first"},
    {"word": "walk", "category": "first"}
  ],
  "suggestedQuestions": [
    {"text": "Does your word have the letter ''e''?", "category": "letters"},
    {"text": "Does your word have the letter ''a''?", "category": "letters"},
    {"text": "Does your word start with a vowel?", "category": "letters"},
    {"text": "Does your word end with a vowel?", "category": "letters"},
    {"text": "Is your word two letters long?", "category": "length"},
    {"text": "Is your word three letters long?", "category": "length"},
    {"text": "Is your word four letters long?", "category": "length"},
    {"text": "Is your word more than four letters?", "category": "length"},
    {"text": "Does your word have a silent letter?", "category": "patterns"},
    {"text": "Does your word end with a consonant blend?", "category": "patterns"},
    {"text": "Does your word have the ''long a'' sound?", "category": "sounds"},
    {"text": "Does your word rhyme with ''old''?", "category": "sounds"},
    {"text": "Is your word something you can do (an action)?", "category": "meaning"},
    {"text": "Does your word describe when something happens?", "category": "meaning"}
  ],
  "settings": {"gridSize": 24, "allowCustomQuestions": true, "turnTimeLimit": 0, "showPhoneticHints": false, "enableSounds": true}
}', TRUE),

('grade-2', '2nd Grade Sight Words', NULL, '{
  "id": "grade-2",
  "name": "2nd Grade Sight Words",
  "description": "Dolch 2nd Grade sight words — more complex high-frequency words for developing readers.",
  "wordBank": [
    {"word": "always", "category": "second"},
    {"word": "around", "category": "second"},
    {"word": "because", "category": "second"},
    {"word": "been", "category": "second"},
    {"word": "before", "category": "second"},
    {"word": "best", "category": "second"},
    {"word": "both", "category": "second"},
    {"word": "buy", "category": "second"},
    {"word": "call", "category": "second"},
    {"word": "does", "category": "second"},
    {"word": "don''t", "category": "second"},
    {"word": "fast", "category": "second"},
    {"word": "first", "category": "second"},
    {"word": "found", "category": "second"},
    {"word": "gave", "category": "second"},
    {"word": "green", "category": "second"},
    {"word": "its", "category": "second"},
    {"word": "made", "category": "second"},
    {"word": "many", "category": "second"},
    {"word": "read", "category": "second"},
    {"word": "sing", "category": "second"},
    {"word": "tell", "category": "second"},
    {"word": "upon", "category": "second"},
    {"word": "wish", "category": "second"}
  ],
  "suggestedQuestions": [
    {"text": "Does your word have the letter ''e''?", "category": "letters"},
    {"text": "Does your word have the letter ''a''?", "category": "letters"},
    {"text": "Does your word start with a vowel?", "category": "letters"},
    {"text": "Does your word end with a vowel?", "category": "letters"},
    {"text": "Is your word three letters long?", "category": "length"},
    {"text": "Is your word four letters long?", "category": "length"},
    {"text": "Is your word more than four letters?", "category": "length"},
    {"text": "Does your word have a double letter?", "category": "patterns"},
    {"text": "Does your word have an apostrophe?", "category": "patterns"},
    {"text": "Does your word end with a silent ''e''?", "category": "patterns"},
    {"text": "Does your word have the ''long e'' sound?", "category": "sounds"},
    {"text": "Does your word have two syllables?", "category": "sounds"},
    {"text": "Is your word something you can do (an action)?", "category": "meaning"},
    {"text": "Does your word describe something (an adjective)?", "category": "meaning"},
    {"text": "Does your word tell when or how often?", "category": "meaning"}
  ],
  "settings": {"gridSize": 24, "allowCustomQuestions": true, "turnTimeLimit": 0, "showPhoneticHints": false, "enableSounds": true}
}', TRUE),

('grade-3', '3rd Grade Sight Words', NULL, '{
  "id": "grade-3",
  "name": "3rd Grade Sight Words",
  "description": "Dolch 3rd Grade and Fry sight words for 3rd graders — advancing toward independent reading.",
  "wordBank": [
    {"word": "about", "category": "third"},
    {"word": "better", "category": "third"},
    {"word": "bring", "category": "third"},
    {"word": "carry", "category": "third"},
    {"word": "clean", "category": "third"},
    {"word": "done", "category": "third"},
    {"word": "draw", "category": "third"},
    {"word": "drink", "category": "third"},
    {"word": "eight", "category": "third"},
    {"word": "fall", "category": "third"},
    {"word": "far", "category": "third"},
    {"word": "full", "category": "third"},
    {"word": "grow", "category": "third"},
    {"word": "hold", "category": "third"},
    {"word": "hurt", "category": "third"},
    {"word": "keep", "category": "third"},
    {"word": "kind", "category": "third"},
    {"word": "laugh", "category": "third"},
    {"word": "light", "category": "third"},
    {"word": "much", "category": "third"},
    {"word": "small", "category": "third"},
    {"word": "start", "category": "third"},
    {"word": "today", "category": "third"},
    {"word": "write", "category": "third"}
  ],
  "suggestedQuestions": [
    {"text": "Does your word have the letter ''e''?", "category": "letters"},
    {"text": "Does your word have the letter ''a''?", "category": "letters"},
    {"text": "Does your word start with a consonant blend (like ''br'' or ''st'')?", "category": "letters"},
    {"text": "Is your word four letters long?", "category": "length"},
    {"text": "Is your word five letters long?", "category": "length"},
    {"text": "Is your word more than five letters?", "category": "length"},
    {"text": "Does your word have a double letter?", "category": "patterns"},
    {"text": "Does your word have a silent letter?", "category": "patterns"},
    {"text": "Does your word end with a consonant blend?", "category": "patterns"},
    {"text": "Does your word have the ''long i'' sound?", "category": "sounds"},
    {"text": "Does your word have two syllables?", "category": "sounds"},
    {"text": "Does your word rhyme with ''all''?", "category": "sounds"},
    {"text": "Is your word something you can do (an action)?", "category": "meaning"},
    {"text": "Does your word describe something (an adjective)?", "category": "meaning"},
    {"text": "Is your word a number?", "category": "meaning"},
    {"text": "Does your word relate to time?", "category": "meaning"}
  ],
  "settings": {"gridSize": 24, "allowCustomQuestions": true, "turnTimeLimit": 0, "showPhoneticHints": false, "enableSounds": true}
}', TRUE),

('grade-4', '4th Grade Sight Words', NULL, '{
  "id": "grade-4",
  "name": "4th Grade Sight Words",
  "description": "Fry 4th Hundred sight words for 4th graders — academic vocabulary for fluent readers.",
  "wordBank": [
    {"word": "across", "category": "fry-fourth"},
    {"word": "body", "category": "fry-fourth"},
    {"word": "check", "category": "fry-fourth"},
    {"word": "city", "category": "fry-fourth"},
    {"word": "close", "category": "fry-fourth"},
    {"word": "early", "category": "fry-fourth"},
    {"word": "earth", "category": "fry-fourth"},
    {"word": "enough", "category": "fry-fourth"},
    {"word": "group", "category": "fry-fourth"},
    {"word": "hard", "category": "fry-fourth"},
    {"word": "idea", "category": "fry-fourth"},
    {"word": "learn", "category": "fry-fourth"},
    {"word": "might", "category": "fry-fourth"},
    {"word": "never", "category": "fry-fourth"},
    {"word": "paper", "category": "fry-fourth"},
    {"word": "plant", "category": "fry-fourth"},
    {"word": "river", "category": "fry-fourth"},
    {"word": "south", "category": "fry-fourth"},
    {"word": "story", "category": "fry-fourth"},
    {"word": "table", "category": "fry-fourth"},
    {"word": "think", "category": "fry-fourth"},
    {"word": "under", "category": "fry-fourth"},
    {"word": "watch", "category": "fry-fourth"},
    {"word": "young", "category": "fry-fourth"}
  ],
  "suggestedQuestions": [
    {"text": "Does your word have the letter ''e''?", "category": "letters"},
    {"text": "Does your word have the letter ''a''?", "category": "letters"},
    {"text": "Does your word start with a vowel?", "category": "letters"},
    {"text": "Does your word have more vowels than consonants?", "category": "letters"},
    {"text": "Is your word five letters long?", "category": "length"},
    {"text": "Is your word more than five letters?", "category": "length"},
    {"text": "Does your word have a double letter?", "category": "patterns"},
    {"text": "Does your word end with a silent ''e''?", "category": "patterns"},
    {"text": "Does your word have a consonant digraph (like ''th'' or ''ch'')?", "category": "patterns"},
    {"text": "Does your word have two syllables?", "category": "sounds"},
    {"text": "Does your word have the ''er'' sound?", "category": "sounds"},
    {"text": "Is your word something you can do (an action)?", "category": "meaning"},
    {"text": "Is your word a thing you can touch?", "category": "meaning"},
    {"text": "Does your word describe something (an adjective)?", "category": "meaning"},
    {"text": "Does your word relate to nature or geography?", "category": "meaning"},
    {"text": "Could your word be used as both a noun and a verb?", "category": "meaning"}
  ],
  "settings": {"gridSize": 24, "allowCustomQuestions": true, "turnTimeLimit": 0, "showPhoneticHints": false, "enableSounds": true}
}', TRUE),

('grade-5', '5th Grade Sight Words', NULL, '{
  "id": "grade-5",
  "name": "5th Grade Sight Words",
  "description": "Fry 5th Hundred sight words for 5th graders — advanced vocabulary for strong, independent readers.",
  "wordBank": [
    {"word": "among", "category": "fry-fifth"},
    {"word": "beauty", "category": "fry-fifth"},
    {"word": "caught", "category": "fry-fifth"},
    {"word": "course", "category": "fry-fifth"},
    {"word": "engine", "category": "fry-fifth"},
    {"word": "field", "category": "fry-fifth"},
    {"word": "figure", "category": "fry-fifth"},
    {"word": "front", "category": "fry-fifth"},
    {"word": "happen", "category": "fry-fifth"},
    {"word": "heavy", "category": "fry-fifth"},
    {"word": "island", "category": "fry-fifth"},
    {"word": "length", "category": "fry-fifth"},
    {"word": "notice", "category": "fry-fifth"},
    {"word": "object", "category": "fry-fifth"},
    {"word": "piece", "category": "fry-fifth"},
    {"word": "picked", "category": "fry-fifth"},
    {"word": "reason", "category": "fry-fifth"},
    {"word": "simple", "category": "fry-fifth"},
    {"word": "square", "category": "fry-fifth"},
    {"word": "stood", "category": "fry-fifth"},
    {"word": "street", "category": "fry-fifth"},
    {"word": "though", "category": "fry-fifth"},
    {"word": "total", "category": "fry-fifth"},
    {"word": "village", "category": "fry-fifth"}
  ],
  "suggestedQuestions": [
    {"text": "Does your word have the letter ''e''?", "category": "letters"},
    {"text": "Does your word have the letter ''a''?", "category": "letters"},
    {"text": "Does your word start with a vowel?", "category": "letters"},
    {"text": "Does your word have more vowels than consonants?", "category": "letters"},
    {"text": "Is your word five letters long?", "category": "length"},
    {"text": "Is your word six letters long?", "category": "length"},
    {"text": "Is your word more than six letters?", "category": "length"},
    {"text": "Does your word have a double letter?", "category": "patterns"},
    {"text": "Does your word have a silent letter?", "category": "patterns"},
    {"text": "Does your word end with a suffix (like ''-ed'' or ''-ing'')?", "category": "patterns"},
    {"text": "Does your word have a consonant digraph (like ''th'' or ''gh'')?", "category": "patterns"},
    {"text": "Does your word have two syllables?", "category": "sounds"},
    {"text": "Does your word have three syllables?", "category": "sounds"},
    {"text": "Is your word something you can do (an action)?", "category": "meaning"},
    {"text": "Is your word a thing you can touch?", "category": "meaning"},
    {"text": "Does your word describe something (an adjective)?", "category": "meaning"},
    {"text": "Is your word a place or location?", "category": "meaning"},
    {"text": "Could your word be used as both a noun and a verb?", "category": "meaning"}
  ],
  "settings": {"gridSize": 24, "allowCustomQuestions": true, "turnTimeLimit": 0, "showPhoneticHints": false, "enableSounds": true}
}', TRUE)

ON CONFLICT (id) DO NOTHING;
